In [24]:
import pandas as pd

In [25]:
A=pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})
A

   Yes   No
0   50  131
1   21    2

In [26]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [27]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [28]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [29]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [30]:
wine_reviews = pd.read_csv("melb_data.csv")

In [31]:
wine_reviews.shape

(13580, 21)

In [32]:
wine_reviews.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [33]:
wine_reviews['Price'].head()

0    1480000.0
1    1035000.0
2    1465000.0
3     850000.0
4    1600000.0
Name: Price, dtype: float64

In [34]:
wine_reviews['Price']

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
           ...
13575    1245000.0
13576    1031000.0
13577    1170000.0
13578    2500000.0
13579    1285000.0
Name: Price, Length: 13580, dtype: float64

In [35]:
wine_reviews['Price'][0] #

1480000.0

In [36]:
wine_reviews.iloc[2,:] #3rd row and all column
#row - column

Suburb                      Abbotsford
Address                   5 Charles St
Rooms                                3
Type                                 h
Price                        1.465e+06
Method                              SP
SellerG                         Biggin
Date                         4/03/2017
Distance                           2.5
Postcode                          3067
Bedroom2                             3
Bathroom                             2
Car                                  0
Landsize                           134
BuildingArea                       150
YearBuilt                         1900
CouncilArea                      Yarra
Lattitude                     -37.8093
Longtitude                     144.994
Regionname       Northern Metropolitan
Propertycount                     4019
Name: 2, dtype: object

In [37]:
wine_reviews.iloc[:, 0]  # all rows and 1st column

0           Abbotsford
1           Abbotsford
2           Abbotsford
3           Abbotsford
4           Abbotsford
             ...
13575    Wheelers Hill
13576     Williamstown
13577     Williamstown
13578     Williamstown
13579       Yarraville
Name: Suburb, Length: 13580, dtype: object

In [38]:
wine_reviews.iloc[:3, 1]  #[row,column] On its own, the : operator, which also comes from native Python, means "everything".

0       85 Turner St
1    25 Bloomburg St
2       5 Charles St
Name: Address, dtype: object

In [39]:
wine_reviews.iloc[1:3, 1] # to select just the second and third entries.

1    25 Bloomburg St
2       5 Charles St
Name: Address, dtype: object

In [40]:
wine_reviews.iloc[[0, 1, 2, 3], 1] #It's also possible to pass a list

0        85 Turner St
1     25 Bloomburg St
2        5 Charles St
3    40 Federation La
Name: Address, dtype: object

In [41]:
#Finally, it's worth knowing that negative numbers can be used in selection.
#This will start counting forwards from the end of the values.
wine_reviews.iloc[-5:,1] #[row,column]

13575     12 Strada Cr
13576    77 Merrett Dr
13577      83 Power St
13578     96 Verdon St
13579       6 Agnes St
Name: Address, dtype: object

## loc

#### The second paradigm for attribute selection is the one followed by the loc operator: label-based selection. In this paradigm, it's the data index value, not its position, which matters.

In [42]:
wine_reviews.loc[:, ['Address', 'Rooms', 'Type']]

                Address  Rooms Type
0          85 Turner St      2    h
1       25 Bloomburg St      2    h
2          5 Charles St      3    h
3      40 Federation La      3    h
4           55a Park St      4    h
...                 ...    ...  ...
13575      12 Strada Cr      4    h
13576     77 Merrett Dr      3    h
13577       83 Power St      3    h
13578      96 Verdon St      4    h
13579        6 Agnes St      4    h

[13580 rows x 3 columns]

In [43]:
wine_reviews.Suburb == 'Abbotsford'

0         True
1         True
2         True
3         True
4         True
         ...
13575    False
13576    False
13577    False
13578    False
13579    False
Name: Suburb, Length: 13580, dtype: bool

In [44]:
wine_reviews.loc[wine_reviews['Suburb'] == 'Abbotsford']

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
5,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,7/05/2016,2.5,3067.0,...,1.0,0.0,181.0,NaN,NaN,Yarra,-37.80410,144.99530,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
7,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
8,Abbotsford,6/241 Nicholson St,1,u,300000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80080,144.99730,Northern Metropolitan,4019.0
9,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,2.0,220.0,75.0,1900.0,Yarra,-37.80100,144.99890,Northern Metropolitan,4019.0
10,Abbotsford,411/8 Grosvenor St,2,u,700000.0,VB,Jellis,12/11/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81100,145.00670,Northern Metropolitan,4019.0
11,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,...,2.0,2.0,214.0,190.0,2005.0,Yarra,-37.80850,144.99640,Northern Metropolitan,4019.0
12,Abbotsford,123/56 Nicholson St,2,u,750000.0,S,Biggin,12/11/2016,2.5,3067.0,...,2.0,1.0,0.0,94.0,2009.0,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
13,Abbotsford,45 William St,2,h,1172500.0,S,Biggin,13/08/2016,2.5,3067.0,...,1.0,1.0,195.0,NaN,NaN,Yarra,-37.80840,144.99730,Northern Metropolitan,4019.0
14,Abbotsford,7/20 Abbotsford St,1,u,441000.0,SP,Greg,14/05/2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80160,144.99880,Northern Metropolitan,4019.0
15,Abbotsford,16 William St,2,h,1310000.0,S,Jellis,15/10/2016,2.5,3067.0,...,1.0,2.0,238.0,97.0,1890.0,Yarra,-37.80900,144.99760,Northern Metropolitan,4019.0
16,Abbotsford,42 Henry St,3,h,1200000.0,S,Jellis,16/07/2016,2.5,3067.0,...,2.0,1.0,113.0,110.0,1880.0,Yarra,-37.80560,144.99300,Northern Metropolitan,4019.0
17,Abbotsford,78 Yarra St,3,h,1176500.0,S,LITTLE,16/07/2016,2.5,3067.0,...,1.0,1.0,138.0,105.0,1890.0,Yarra,-37.80210,144.99650,Northern Metropolitan,4019.0
18,Abbotsford,196 Nicholson St,3,h,955000.0,S,Collins,17/09/2016,2.5,3067.0,...,1.0,0.0,183.0,NaN,NaN,Yarra,-37.80220,144.99750,Northern Metropolitan,4019.0
19,Abbotsford,42 Valiant St,2,h,890000.0,S,Biggin,17/09/2016,2.5,3067.0,...,1.0,1.0,150.0,73.0,1985.0,Yarra,-37.80110,145.00040,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.0,1900.0,Yarra,-37.80730,144.99520,Northern Metropolitan,4019.0
21,Abbotsford,13/11 Nicholson St,3,t,900000.0,S,Beller,18/03/2017,2.5,3067.0,...,2.0,2.0,0.0,NaN,2010.0,Yarra,-37.80930,144.99590,Northern Metropolitan,4019.0
22,Abbotsford,138/56 Nicholson St,3,u,1090000.0,S,Jellis,18/03/2017,2.5,3067.0,...,2.0,2.0,4290.0,27.0,NaN,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
23,Abbotsford,6/219 Nicholson St,2,u,500000.0,S,Collins,18/06/2016,2.5,3067.0,...,1.0,1.0,0.0,60.0,1970.0,Yarra,-37.80150,144.99720,Northern Metropolitan,4019.0
24,Abbotsford,52a William St,2,h,1100000.0,PI,Biggin,18/06/2016,2.5,3067.0,...,2.0,1.0,124.0,135.0,2013.0,Yarra,-37.80790,144.99770,Northern Metropolitan,4019.0
25,Abbotsford,49 Park St,2,h,1315000.0,S,Marshall,19/11/2016,2.5,3067.0,...,1.0,0.0,147.0,85.0,1900.0,Yarra,-37.80800,144.99400,Northern Metropolitan,4019.0
26,Abbotsford,5/20 Abbotsford St,1,u,426000.0,SP,Greg,22/08/2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80160,144.99880,Northern Metropolitan,4019.0
27,Abbotsford,48 Abbotsford St,3,h,1447500.0,PI,Nelson,22/08/2016,2.5,3067.0,...,3.0,1.0,166.0,174.0,2012.0,Yarra,-37.80170,145.00010,Northern Metropolitan,4019.0
28,Abbotsford,116/56 Nicholson St,1,u,457000.0,S,Jellis,22/08/2016,2.5,3067.0,...,1.0,1.0,0.0,50.0,NaN,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
29,Abbotsford,159 Park St,2,h,1135000.0,S,Nelson,22/08/2016,2.5,3067.0,...,2.0,2.0,98.0,128.0,1920.0,Yarra,-37.80050,144.99520,Northern Metropolitan,4019.0
30,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,3.0,1.0,0.0,NaN,NaN,Yarra,-37.79940,144.99650,Northern Metropolitan,4019.0
31,Abbotsford,166 Gipps St,3,h,1290000.0,S,Biggin,25/02/2017,2.5,3067.0,...,2.0,2.0,147.0,18.0,NaN,Yarra,-37.80500,144.99430,Northern Metropolitan,4019.0
32,Abbotsford,60 Stafford St,3,h,1290000.0,S,Biggin,25/02/2017,2.5,3067.0,...,1.0,1.0,168.0,124.0,1950.0,Yarra,-37.80070,144.99580,Northern Metropolitan,4019.0
33,Abbotsford,11/205 Gipps St,1,u,470000.0,S,Nelson,26/07/2016,2.5,3067.0,...,1.0,1.0,0.0,50.0,2013.0,Yarra,-37.80550,144.99610,Northern Metropolitan,4019.0
34,Abbotsford,47 Studley St,2,h,1180000.0,S,Jellis,27/11/2016,2.5,3067.0,...,1.0,0.0,162.0,91.0,1900.0,Yarra,-37.80160,144.99560,Northern Metropolitan,4019.0
35,Abbotsford,45 Yarra St,3,h,1195000.0,SP,Jellis,27/11/2016,2.5,3067.0,...,2.0,1.0,120.0,128.0,1998.0,Yarra,-37.80220,144.99540,Northern Metropolitan,4019.0
36,Abbotsford,200 Nicholson St,2,h,1012500.0,S,Nelson,28/05/2016,2.5,3067.0,...,1.0,0.0,182.0,82.0,1900.0,Yarra,-37.80210,144.99760,Northern Metropolitan,4019.0
37,Abbotsford,27 Charles St,2,h,1030000.0,S,Biggin,30/07/2016,2.5,3067.0,...,1.0,1.0,172.0,81.0,1930.0,Yarra,-37.80860,144.99460,Northern Metropolitan,4019.0
8549,Abbotsford,132 Vere St,3,h,1000000.0,SP,Biggin,8/04/2017,2.5,3067.0,...,1.0,0.0,198.0,98.0,1900.0,Yarra,-37.80250,144.99390,Northern Metropolitan,4019.0
8550,Abbotsford,6/205 Gipps St,2,u,870000.0,S,Biggin,20/05/2017,2.5,3067.0,...,2.0,1.0,0.0,86.0,2013.0,Yarra,-37.80550,144.99610,Northern Metropolitan,4019.0
8551,Abbotsford,24 Cooke St,2,h,1050000.0,S,Jellis,29/04/2017,2.5,3067.0,...,1.0,0.0,129.0,128.0,1890.0,Yarra,-37.80990,145.00270,Northern Metropolitan,4019.0
8552,Abbotsford,198 Gipps St,2,h,1242000.0,S,Nelson,29/04/2017,2.5,3067.0,...,1.0,1.0,249.0,98.0,1940.0,Yarra,-37.80520,144.99630,Northern Metropolitan,4019.0
8553,Abbotsford,22 Lulie St,3,h,1165000.0,S,Jellis,29/04/2017,2.5,3067.0,...,2.0,0.0,92.0,114.0,1888.0,Yarra,-37.79700,144.99570,Northern Metropolitan,4019.0
9390,Abbotsford,5/29 Church St,2,u,480000.0,S,hockingstuart,17/06/2017,3.0,3067.0,...,1.0,1.0,601.0,64.0,1970.0,Yarra,-37.80915,145.00066,Northern Metropolitan,4019.0
9391,Abbotsford,14/205 Gipps St,2,u,750000.0,SP,Jellis,17/06/2017,3.0,3067.0,...,1.0,1.0,2379.0,69.0,2013.0,Yarra,-37.80554,144.99612,Northern Metropolitan,4019.0
9764,Abbotsford,2 Federation La,3,h,855000.0,S,Nelson,24/06/2017,3.0,3067.0,...,2.0,1.0,92.0,116.0,2004.0,Yarra,-37.79683,144.99586,Northern Metropolitan,4019.0
10093,Abbotsford,1/43 Abbotsford St,2,u,505000.0,PI,Nelson,27/05/2017,3.0,3067.0,...,1.0,1.0,0.0,38.0,1970.0,Yarra,-37.80206,145.00015,Northern Metropolitan,4019.0
10094,Abbotsford,67 Yarra St,3,h,1402500.0,S,Jellis,27/05/2017,3.0,3067.0,...,1.0,1.0,270.0,101.0,1960.0,Yarra,-37.80230,144.99615,Northern Metropolitan,4019.0
10566,Abbotsford,21/659 Victoria St,2,u,550000.0,S,hockingstuart,8/07/2017,3.0,3067.0,...,1.0,1.0,1521.0,NaN,NaN,Yarra,-37.81140,145.01163,Northern Metropolitan,4019.0
10876,Abbotsford,143 Charles St,3,h,1635000.0,S,Nelson,12/08/2017,3.0,3067.0,...,1.0,0.0,142.0,130.0,1880.0,Yarra,-37.80359,144.99538,Northern Metropolitan,4019.0
10877,Abbotsford,10 James St,2,h,940000.0,S,Biggin,12/08/2017,3.0,3067.0,...,1.0,0.0,424.0,NaN,NaN,Yarra,-37.80911,144.99339,Northern Metropolitan,4019.0
10878,Abbotsford,17 Valiant St,3,h,1375000.0,S,hockingstuart,12/08/2017,3.0,3067.0,...,1.0,0.0,299.0,NaN,NaN,Yarra,-37.80125,144.99926,Northern Metropolitan,4019.0
10879,Abbotsford,1/50 Valiant St,4,t,1525000.0,S,Jellis,12/08/2017,3.0,3067.0,...,2.0,2.0,102.0,NaN,NaN,Yarra,-37.80116,145.00066,Northern Metropolitan,4019.0
11555,Abbotsford,101 Charles St,2,h,911000.0,S,Purplebricks,22/07/2017,3.0,3067.0,...,1.0,0.0,141.0,NaN,NaN,Yarra,-37.80586,144.99499,Northern Metropolitan,4019.0
11556,Abbotsford,133 Yarra St,2,h,1190000.0,S,Biggin,22/07/2017,3.0,3067.0,...,2.0,1.0,147.0,175.0,2000.0,Yarra,-37.80269,145.00010,Northern Metropolitan,4019.0
12886,Abbotsford,67 Stafford St,3,h,1000000.0,PI,Biggin,19/08/2017,3.0,3067.0,...,1.0,2.0,196.0,NaN,1900.0,NaN,-37.80094,144.99569,Northern Metropolitan,4019.0

In [45]:
wine_reviews[wine_reviews['Suburb']=='Abbotsford']

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
5,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,7/05/2016,2.5,3067.0,...,1.0,0.0,181.0,NaN,NaN,Yarra,-37.80410,144.99530,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
7,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
8,Abbotsford,6/241 Nicholson St,1,u,300000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80080,144.99730,Northern Metropolitan,4019.0
9,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,2.0,220.0,75.0,1900.0,Yarra,-37.80100,144.99890,Northern Metropolitan,4019.0
10,Abbotsford,411/8 Grosvenor St,2,u,700000.0,VB,Jellis,12/11/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81100,145.00670,Northern Metropolitan,4019.0
11,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,...,2.0,2.0,214.0,190.0,2005.0,Yarra,-37.80850,144.99640,Northern Metropolitan,4019.0
12,Abbotsford,123/56 Nicholson St,2,u,750000.0,S,Biggin,12/11/2016,2.5,3067.0,...,2.0,1.0,0.0,94.0,2009.0,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
13,Abbotsford,45 William St,2,h,1172500.0,S,Biggin,13/08/2016,2.5,3067.0,...,1.0,1.0,195.0,NaN,NaN,Yarra,-37.80840,144.99730,Northern Metropolitan,4019.0
14,Abbotsford,7/20 Abbotsford St,1,u,441000.0,SP,Greg,14/05/2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80160,144.99880,Northern Metropolitan,4019.0
15,Abbotsford,16 William St,2,h,1310000.0,S,Jellis,15/10/2016,2.5,3067.0,...,1.0,2.0,238.0,97.0,1890.0,Yarra,-37.80900,144.99760,Northern Metropolitan,4019.0
16,Abbotsford,42 Henry St,3,h,1200000.0,S,Jellis,16/07/2016,2.5,3067.0,...,2.0,1.0,113.0,110.0,1880.0,Yarra,-37.80560,144.99300,Northern Metropolitan,4019.0
17,Abbotsford,78 Yarra St,3,h,1176500.0,S,LITTLE,16/07/2016,2.5,3067.0,...,1.0,1.0,138.0,105.0,1890.0,Yarra,-37.80210,144.99650,Northern Metropolitan,4019.0
18,Abbotsford,196 Nicholson St,3,h,955000.0,S,Collins,17/09/2016,2.5,3067.0,...,1.0,0.0,183.0,NaN,NaN,Yarra,-37.80220,144.99750,Northern Metropolitan,4019.0
19,Abbotsford,42 Valiant St,2,h,890000.0,S,Biggin,17/09/2016,2.5,3067.0,...,1.0,1.0,150.0,73.0,1985.0,Yarra,-37.80110,145.00040,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.0,1900.0,Yarra,-37.80730,144.99520,Northern Metropolitan,4019.0
21,Abbotsford,13/11 Nicholson St,3,t,900000.0,S,Beller,18/03/2017,2.5,3067.0,...,2.0,2.0,0.0,NaN,2010.0,Yarra,-37.80930,144.99590,Northern Metropolitan,4019.0
22,Abbotsford,138/56 Nicholson St,3,u,1090000.0,S,Jellis,18/03/2017,2.5,3067.0,...,2.0,2.0,4290.0,27.0,NaN,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
23,Abbotsford,6/219 Nicholson St,2,u,500000.0,S,Collins,18/06/2016,2.5,3067.0,...,1.0,1.0,0.0,60.0,1970.0,Yarra,-37.80150,144.99720,Northern Metropolitan,4019.0
24,Abbotsford,52a William St,2,h,1100000.0,PI,Biggin,18/06/2016,2.5,3067.0,...,2.0,1.0,124.0,135.0,2013.0,Yarra,-37.80790,144.99770,Northern Metropolitan,4019.0
25,Abbotsford,49 Park St,2,h,1315000.0,S,Marshall,19/11/2016,2.5,3067.0,...,1.0,0.0,147.0,85.0,1900.0,Yarra,-37.80800,144.99400,Northern Metropolitan,4019.0
26,Abbotsford,5/20 Abbotsford St,1,u,426000.0,SP,Greg,22/08/2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80160,144.99880,Northern Metropolitan,4019.0
27,Abbotsford,48 Abbotsford St,3,h,1447500.0,PI,Nelson,22/08/2016,2.5,3067.0,...,3.0,1.0,166.0,174.0,2012.0,Yarra,-37.80170,145.00010,Northern Metropolitan,4019.0
28,Abbotsford,116/56 Nicholson St,1,u,457000.0,S,Jellis,22/08/2016,2.5,3067.0,...,1.0,1.0,0.0,50.0,NaN,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
29,Abbotsford,159 Park St,2,h,1135000.0,S,Nelson,22/08/2016,2.5,3067.0,...,2.0,2.0,98.0,128.0,1920.0,Yarra,-37.80050,144.99520,Northern Metropolitan,4019.0
30,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,3.0,1.0,0.0,NaN,NaN,Yarra,-37.79940,144.99650,Northern Metropolitan,4019.0
31,Abbotsford,166 Gipps St,3,h,1290000.0,S,Biggin,25/02/2017,2.5,3067.0,...,2.0,2.0,147.0,18.0,NaN,Yarra,-37.80500,144.99430,Northern Metropolitan,4019.0
32,Abbotsford,60 Stafford St,3,h,1290000.0,S,Biggin,25/02/2017,2.5,3067.0,...,1.0,1.0,168.0,124.0,1950.0,Yarra,-37.80070,144.99580,Northern Metropolitan,4019.0
33,Abbotsford,11/205 Gipps St,1,u,470000.0,S,Nelson,26/07/2016,2.5,3067.0,...,1.0,1.0,0.0,50.0,2013.0,Yarra,-37.80550,144.99610,Northern Metropolitan,4019.0
34,Abbotsford,47 Studley St,2,h,1180000.0,S,Jellis,27/11/2016,2.5,3067.0,...,1.0,0.0,162.0,91.0,1900.0,Yarra,-37.80160,144.99560,Northern Metropolitan,4019.0
35,Abbotsford,45 Yarra St,3,h,1195000.0,SP,Jellis,27/11/2016,2.5,3067.0,...,2.0,1.0,120.0,128.0,1998.0,Yarra,-37.80220,144.99540,Northern Metropolitan,4019.0
36,Abbotsford,200 Nicholson St,2,h,1012500.0,S,Nelson,28/05/2016,2.5,3067.0,...,1.0,0.0,182.0,82.0,1900.0,Yarra,-37.80210,144.99760,Northern Metropolitan,4019.0
37,Abbotsford,27 Charles St,2,h,1030000.0,S,Biggin,30/07/2016,2.5,3067.0,...,1.0,1.0,172.0,81.0,1930.0,Yarra,-37.80860,144.99460,Northern Metropolitan,4019.0
8549,Abbotsford,132 Vere St,3,h,1000000.0,SP,Biggin,8/04/2017,2.5,3067.0,...,1.0,0.0,198.0,98.0,1900.0,Yarra,-37.80250,144.99390,Northern Metropolitan,4019.0
8550,Abbotsford,6/205 Gipps St,2,u,870000.0,S,Biggin,20/05/2017,2.5,3067.0,...,2.0,1.0,0.0,86.0,2013.0,Yarra,-37.80550,144.99610,Northern Metropolitan,4019.0
8551,Abbotsford,24 Cooke St,2,h,1050000.0,S,Jellis,29/04/2017,2.5,3067.0,...,1.0,0.0,129.0,128.0,1890.0,Yarra,-37.80990,145.00270,Northern Metropolitan,4019.0
8552,Abbotsford,198 Gipps St,2,h,1242000.0,S,Nelson,29/04/2017,2.5,3067.0,...,1.0,1.0,249.0,98.0,1940.0,Yarra,-37.80520,144.99630,Northern Metropolitan,4019.0
8553,Abbotsford,22 Lulie St,3,h,1165000.0,S,Jellis,29/04/2017,2.5,3067.0,...,2.0,0.0,92.0,114.0,1888.0,Yarra,-37.79700,144.99570,Northern Metropolitan,4019.0
9390,Abbotsford,5/29 Church St,2,u,480000.0,S,hockingstuart,17/06/2017,3.0,3067.0,...,1.0,1.0,601.0,64.0,1970.0,Yarra,-37.80915,145.00066,Northern Metropolitan,4019.0
9391,Abbotsford,14/205 Gipps St,2,u,750000.0,SP,Jellis,17/06/2017,3.0,3067.0,...,1.0,1.0,2379.0,69.0,2013.0,Yarra,-37.80554,144.99612,Northern Metropolitan,4019.0
9764,Abbotsford,2 Federation La,3,h,855000.0,S,Nelson,24/06/2017,3.0,3067.0,...,2.0,1.0,92.0,116.0,2004.0,Yarra,-37.79683,144.99586,Northern Metropolitan,4019.0
10093,Abbotsford,1/43 Abbotsford St,2,u,505000.0,PI,Nelson,27/05/2017,3.0,3067.0,...,1.0,1.0,0.0,38.0,1970.0,Yarra,-37.80206,145.00015,Northern Metropolitan,4019.0
10094,Abbotsford,67 Yarra St,3,h,1402500.0,S,Jellis,27/05/2017,3.0,3067.0,...,1.0,1.0,270.0,101.0,1960.0,Yarra,-37.80230,144.99615,Northern Metropolitan,4019.0
10566,Abbotsford,21/659 Victoria St,2,u,550000.0,S,hockingstuart,8/07/2017,3.0,3067.0,...,1.0,1.0,1521.0,NaN,NaN,Yarra,-37.81140,145.01163,Northern Metropolitan,4019.0
10876,Abbotsford,143 Charles St,3,h,1635000.0,S,Nelson,12/08/2017,3.0,3067.0,...,1.0,0.0,142.0,130.0,1880.0,Yarra,-37.80359,144.99538,Northern Metropolitan,4019.0
10877,Abbotsford,10 James St,2,h,940000.0,S,Biggin,12/08/2017,3.0,3067.0,...,1.0,0.0,424.0,NaN,NaN,Yarra,-37.80911,144.99339,Northern Metropolitan,4019.0
10878,Abbotsford,17 Valiant St,3,h,1375000.0,S,hockingstuart,12/08/2017,3.0,3067.0,...,1.0,0.0,299.0,NaN,NaN,Yarra,-37.80125,144.99926,Northern Metropolitan,4019.0
10879,Abbotsford,1/50 Valiant St,4,t,1525000.0,S,Jellis,12/08/2017,3.0,3067.0,...,2.0,2.0,102.0,NaN,NaN,Yarra,-37.80116,145.00066,Northern Metropolitan,4019.0
11555,Abbotsford,101 Charles St,2,h,911000.0,S,Purplebricks,22/07/2017,3.0,3067.0,...,1.0,0.0,141.0,NaN,NaN,Yarra,-37.80586,144.99499,Northern Metropolitan,4019.0
11556,Abbotsford,133 Yarra St,2,h,1190000.0,S,Biggin,22/07/2017,3.0,3067.0,...,2.0,1.0,147.0,175.0,2000.0,Yarra,-37.80269,145.00010,Northern Metropolitan,4019.0
12886,Abbotsford,67 Stafford St,3,h,1000000.0,PI,Biggin,19/08/2017,3.0,3067.0,...,1.0,2.0,196.0,NaN,1900.0,NaN,-37.80094,144.99569,Northern Metropolitan,4019.0

In [46]:
wine_reviews

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [47]:
wine_reviews.loc[(wine_reviews.Suburb == 'Abbotsford') & (wine_reviews.Rooms>=3)]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
11,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,...,2.0,2.0,214.0,190.0,2005.0,Yarra,-37.80850,144.99640,Northern Metropolitan,4019.0
16,Abbotsford,42 Henry St,3,h,1200000.0,S,Jellis,16/07/2016,2.5,3067.0,...,2.0,1.0,113.0,110.0,1880.0,Yarra,-37.80560,144.99300,Northern Metropolitan,4019.0
17,Abbotsford,78 Yarra St,3,h,1176500.0,S,LITTLE,16/07/2016,2.5,3067.0,...,1.0,1.0,138.0,105.0,1890.0,Yarra,-37.80210,144.99650,Northern Metropolitan,4019.0
18,Abbotsford,196 Nicholson St,3,h,955000.0,S,Collins,17/09/2016,2.5,3067.0,...,1.0,0.0,183.0,NaN,NaN,Yarra,-37.80220,144.99750,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.0,1900.0,Yarra,-37.80730,144.99520,Northern Metropolitan,4019.0
21,Abbotsford,13/11 Nicholson St,3,t,900000.0,S,Beller,18/03/2017,2.5,3067.0,...,2.0,2.0,0.0,NaN,2010.0,Yarra,-37.80930,144.99590,Northern Metropolitan,4019.0
22,Abbotsford,138/56 Nicholson St,3,u,1090000.0,S,Jellis,18/03/2017,2.5,3067.0,...,2.0,2.0,4290.0,27.0,NaN,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
27,Abbotsford,48 Abbotsford St,3,h,1447500.0,PI,Nelson,22/08/2016,2.5,3067.0,...,3.0,1.0,166.0,174.0,2012.0,Yarra,-37.80170,145.00010,Northern Metropolitan,4019.0
30,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,3.0,1.0,0.0,NaN,NaN,Yarra,-37.79940,144.99650,Northern Metropolitan,4019.0
31,Abbotsford,166 Gipps St,3,h,1290000.0,S,Biggin,25/02/2017,2.5,3067.0,...,2.0,2.0,147.0,18.0,NaN,Yarra,-37.80500,144.99430,Northern Metropolitan,4019.0
32,Abbotsford,60 Stafford St,3,h,1290000.0,S,Biggin,25/02/2017,2.5,3067.0,...,1.0,1.0,168.0,124.0,1950.0,Yarra,-37.80070,144.99580,Northern Metropolitan,4019.0
35,Abbotsford,45 Yarra St,3,h,1195000.0,SP,Jellis,27/11/2016,2.5,3067.0,...,2.0,1.0,120.0,128.0,1998.0,Yarra,-37.80220,144.99540,Northern Metropolitan,4019.0
8549,Abbotsford,132 Vere St,3,h,1000000.0,SP,Biggin,8/04/2017,2.5,3067.0,...,1.0,0.0,198.0,98.0,1900.0,Yarra,-37.80250,144.99390,Northern Metropolitan,4019.0
8553,Abbotsford,22 Lulie St,3,h,1165000.0,S,Jellis,29/04/2017,2.5,3067.0,...,2.0,0.0,92.0,114.0,1888.0,Yarra,-37.79700,144.99570,Northern Metropolitan,4019.0
9764,Abbotsford,2 Federation La,3,h,855000.0,S,Nelson,24/06/2017,3.0,3067.0,...,2.0,1.0,92.0,116.0,2004.0,Yarra,-37.79683,144.99586,Northern Metropolitan,4019.0
10094,Abbotsford,67 Yarra St,3,h,1402500.0,S,Jellis,27/05/2017,3.0,3067.0,...,1.0,1.0,270.0,101.0,1960.0,Yarra,-37.80230,144.99615,Northern Metropolitan,4019.0
10876,Abbotsford,143 Charles St,3,h,1635000.0,S,Nelson,12/08/2017,3.0,3067.0,...,1.0,0.0,142.0,130.0,1880.0,Yarra,-37.80359,144.99538,Northern Metropolitan,4019.0
10878,Abbotsford,17 Valiant St,3,h,1375000.0,S,hockingstuart,12/08/2017,3.0,3067.0,...,1.0,0.0,299.0,NaN,NaN,Yarra,-37.80125,144.99926,Northern Metropolitan,4019.0
10879,Abbotsford,1/50 Valiant St,4,t,1525000.0,S,Jellis,12/08/2017,3.0,3067.0,...,2.0,2.0,102.0,NaN,NaN,Yarra,-37.80116,145.00066,Northern Metropolitan,4019.0
12886,Abbotsford,67 Stafford St,3,h,1000000.0,PI,Biggin,19/08/2017,3.0,3067.0,...,1.0,2.0,196.0,NaN,1900.0,NaN,-37.80094,144.99569,Northern Metropolitan,4019.0

In [48]:
wine_reviews.loc[(wine_reviews.Suburb == 'Abbotsford') | (wine_reviews.Rooms>=3)]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [49]:
wine_reviews.loc[wine_reviews.Suburb.isin(['Abbotsford', 'Williamstown'])]

# isin is lets you select data whose value "is in" a list of values.

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13084,Williamstown,54 Victoria St,5,h,2550000.0,PI,Williams,19/08/2017,6.8,3016.0,...,2.0,2.0,840.0,244.0,1910.0,NaN,-37.86330,144.88871,Western Metropolitan,6380.0
13329,Williamstown,146 Ferguson St,3,h,832000.0,S,Williams,23/09/2017,6.8,3016.0,...,1.0,1.0,269.0,NaN,NaN,NaN,-37.85808,144.89268,Western Metropolitan,6380.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0

In [50]:
wine_reviews.loc[wine_reviews.Car.notnull()]
#These methods let you highlight values which are (or are not) empty (NaN)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [51]:
wine_reviews.Suburb.describe()

count         13580
unique          314
top       Reservoir
freq            359
Name: Suburb, dtype: object

In [52]:
wine_reviews.Rooms.mean()

2.9379970544919

In [53]:
wine_reviews.Suburb.unique()

array(['Abbotsford', 'Airport West', 'Albert Park', 'Alphington',
       'Altona', 'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton',
       'Ashwood', 'Avondale Heights', 'Balaclava', 'Balwyn',
       'Balwyn North', 'Bentleigh', 'Bentleigh East', 'Box Hill',
       'Braybrook', 'Brighton', 'Brighton East', 'Brunswick',
       'Brunswick West', 'Bulleen', 'Burwood', 'Camberwell', 'Canterbury',
       'Carlton North', 'Carnegie', 'Caulfield', 'Caulfield North',
       'Caulfield South', 'Chadstone', 'Clifton Hill', 'Coburg',
       'Coburg North', 'Collingwood', 'Doncaster', 'Eaglemont',
       'Elsternwick', 'Elwood', 'Essendon', 'Essendon North', 'Fairfield',
       'Fitzroy', 'Fitzroy North', 'Flemington', 'Footscray', 'Glen Iris',
       'Glenroy', 'Gowanbrae', 'Hadfield', 'Hampton', 'Hampton East',
       'Hawthorn', 'Heidelberg Heights', 'Heidelberg West', 'Hughesdale',
       'Ivanhoe', 'Kealba', 'Keilor East', 'Kensington', 'Kew',
       'Kew East', 'Kooyong', 'Maidstone', 'Malvern', 'Malvern East',
       'Maribyrnong', 'Melbourne', 'Middle Park', 'Mont Albert',
       'Moonee Ponds', 'Moorabbin', 'Newport', 'Niddrie',
       'North Melbourne', 'Northcote', 'Oak Park', 'Oakleigh South',
       'Parkville', 'Pascoe Vale', 'Port Melbourne', 'Prahran', 'Preston',
       'Reservoir', 'Richmond', 'Rosanna', 'Seddon', 'South Melbourne',
       'South Yarra', 'Southbank', 'Spotswood', 'St Kilda', 'Strathmore',
       'Sunshine', 'Sunshine North', 'Sunshine West', 'Surrey Hills',
       'Templestowe Lower', 'Thornbury', 'Toorak', 'Viewbank', 'Watsonia',
       'West Melbourne', 'Williamstown', 'Williamstown North', 'Windsor',
       'Yallambie', 'Yarraville', 'Aberfeldie', 'Bellfield',
       'Brunswick East', 'Burnley', 'Campbellfield', 'Carlton',
       'East Melbourne', 'Essendon West', 'Fawkner', 'Hawthorn East',
       'Heidelberg', 'Ivanhoe East', 'Jacana', 'Kingsbury', 'Kingsville',
       'Murrumbeena', 'Ormond', 'West Footscray', 'Albion', 'Brooklyn',
       'Glen Huntly', 'Oakleigh', 'Ripponlea', 'Cremorne', 'Docklands',
       'South Kingsville', 'Strathmore Heights', 'Travancore',
       'Caulfield East', 'Seaholme', 'Keilor Park', 'Gardenvale',
       'Princes Hill', 'Bayswater', 'Bayswater North', 'Beaumaris',
       'Berwick', 'Boronia', 'Briar Hill', 'Broadmeadows', 'Bundoora',
       'Burnside Heights', 'Burwood East', 'Cairnlea', 'Caroline Springs',
       'Cheltenham', 'Craigieburn', 'Cranbourne', 'Croydon', 'Dandenong',
       'Dandenong North', 'Diamond Creek', 'Dingley Village',
       'Doncaster East', 'Donvale', 'Doreen', 'Eltham', 'Epping',
       'Forest Hill', 'Frankston', 'Frankston North', 'Frankston South',
       'Gisborne', 'Gladstone Park', 'Greensborough', 'Hallam',
       'Healesville', 'Highett', 'Hillside', 'Huntingdale',
       'Keilor Downs', 'Keilor Lodge', 'Keysborough', 'Kings Park',
       'Lalor', 'Lower Plenty', 'Melton', 'Mernda', 'Mill Park',
       'Mitcham', 'Montmorency', 'Mordialloc', 'Mount Waverley',
       'Narre Warren', 'Nunawading', 'Oakleigh East', 'Parkdale',
       'Point Cook', 'Ringwood East', 'Rockbank', 'Rowville',
       'Sandringham', 'Seaford', 'Skye', 'South Morang', 'Springvale',
       'St Albans', 'Sunbury', 'Tarneit', 'Taylors Hill', 'Taylors Lakes',
       'The Basin', 'Thomastown', 'Truganina', 'Tullamarine', 'Vermont',
       'Wantirna', 'Wantirna South', 'Werribee', 'Westmeadows',
       'Williams Landing', 'Wollert', 'Wyndham Vale', 'Black Rock',
       'Blackburn', 'Blackburn North', 'Bonbeach', 'Carrum', 'Chelsea',
       'Clayton', 'Doveton', 'Ferntree Gully', 'Glen Waverley',
       'Greenvale', 'Heathmont', 'Hoppers Crossing', 'McKinnon',
       'Melton South', 'Melton West', 'Mentone', 'Mooroolbark',
       'Mulgrave', 'Ringwood', 'Roxburgh Park', 'Seabrook', 'Templestowe',
       'Vermont South', 'Warrandyte', 'Watsonia North', 'Wheelers Hill',
       'Altona Meadows', 'Blackburn South', 'Carrum Downs',
       'Clayton South', 'Croydon North', 'Langwarrin', 'Noble Park',
       'Notting Hill', 'Ringwood North', 'Sydenham', 'Albanvale',
       'Beaconsfield Upper', 'Chelsea Heights', 'Dallas', 'Deer Park',
       'Eltham North', 'Keilor', 'Meadow Heights', 'Mount Evelyn',
       'North Warrandyte', 'Pakenham', 'Riddells Creek', 'Sandhurst',
       'Scoresby', 'Silvan', 'Aspendale', 'Chirnside Park',
       'Croydon Hills', 'Croydon South', 'Derrimut', 'Diggers Rest',
       'Edithvale', 'Hampton Park', 'Knoxfield', 'St Helena', 'Upwey',
       'Bacchus Marsh', 'Coolaroo', 'Cranbourne North', 'Kilsyth',
       'Montrose', 'Aspendale Gardens', 'Bullengarook', 'Clarinda',
       'Deepdene', 'Delahey', 'Hurstbridge', 'Kurunjang', 'Wonga Park',
       'Endeavour Hills', 'Officer', 'Waterways', 'Ardeer',
       'Beaconsfield', 'Springvale South', 'Yarra Glen', 'Brookfield',
       'Emerald', 'Whittlesea', 'Burnside', 'Attwood', 'Wallan',
       'New Gisborne', 'Plumpton', 'Monbulk'], dtype=object)

In [54]:
wine_reviews.Suburb.value_counts()

Reservoir         359
Richmond          260
Bentleigh East    249
Preston           239
Brunswick         222
                 ...
Sandhurst           1
Rockbank            1
Whittlesea          1
New Gisborne        1
Bacchus Marsh       1
Name: Suburb, Length: 314, dtype: int64

#### A map is a term, borrowed from mathematics, for a function that takes one set of values and "maps" them to another set of values. In data science we often have a need for creating new representations from existing data, or for transforming data from the format it is in now to the format that we want it to be in later. Maps are what handle this work, making them extremely important for getting your work done!

In [55]:
wine_review_Rooms_mean = wine_reviews.Rooms.mean()
wine_reviews.Rooms.map(lambda p: p - wine_review_Rooms_mean)

0       -0.937997
1       -0.937997
2        0.062003
3        0.062003
4        1.062003
           ...
13575    1.062003
13576    0.062003
13577    0.062003
13578    1.062003
13579    1.062003
Name: Rooms, Length: 13580, dtype: float64

In [56]:
reviews = pd.read_csv("winemag-data-130k-v2.csv",index_col=0)

In [57]:
def stars(row):
    if row.country == 'Canada':
        return 3
    elif row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1

star_ratings = reviews.apply(stars, axis='columns')
star_ratings

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Length: 129971, dtype: int64

In [58]:
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## Groupwise analysis.............................................................

One function we've been using heavily thus far is the value_counts() function. We can replicate what value_counts() does by doing the following:

In [59]:
reviews.groupby('points').points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [60]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [61]:
reviews.groupby('country').apply(lambda df: df.description.iloc[0])

country
Argentina                 Baked plum, molasses, balsamic vinegar and che...
Armenia                   Medium straw in the glass, this wine has a nos...
Australia                 This medium-bodied Chardonnay features aromas ...
Austria                   Freshness characterizes the nose: green pear, ...
Bosnia and Herzegovina    Toasted oak and cedar notes meld into lush, ri...
Brazil                    Pear, apple and wet-stone aromas are tight, wh...
Bulgaria                  This pale-pink rosé is comprised of 70% Pinot ...
Canada                    An aromatic knockout with notes of peach, papa...
Chile                     White flower, lychee and apple aromas carry th...
China                     This deep ruby-colored wine features a bouquet...
Croatia                   Salt air, lemon pith and lemon blossom lead in...
Cyprus                    An alluring nose of apples, flowers and citrus...
Czech Republic            Smoke and struck-flint notes add a dark tone t...
Egypt                     Ripe pear, apple and tropical fruit in the nos...
England                   A mix of fruity notes immediately hit: white c...
France                    This dry and restrained wine offers spice in p...
Georgia                   Deep ruby in the glass, this wine offers a bou...
Germany                   Savory dried thyme notes accent sunnier flavor...
Greece                    Lively aromas of lemon, grapefruit and melon s...
Hungary                   From a vineyard in Northern Tokaj this dry Fur...
India                     The nose carries notes of cassis, blackberry a...
Israel                    This wine features pleasing aromas of raspberr...
Italy                     Aromas include tropical fruit, broom, brimston...
Lebanon                   Violet red to the eye, this wine is a blend of...
Luxembourg                This non vintage white blend is composed of 50...
Macedonia                 Snappy lemon, grapefruit and apples aromas lea...
Mexico                    The color is appropriately light, the aromas a...
Moldova                   This zesty Moldovan Feteasca Regala has aromas...
Morocco                   Deep garnet to the eye, this wine offers a nos...
New Zealand               The Stoneleigh style traditionally favors ripe...
Peru                      Aromas of freshly laid asphalt and char-grille...
Portugal                  This is ripe and fruity, a wine that is smooth...
Romania                   Fragrant on the nose with fresh orange, lemon ...
Serbia                    This white wine from Serbia has aromas of cara...
Slovakia                  Delicious scents of honey, apples and petrol l...
Slovenia                  Earthy with hints of roasted nuts and dried he...
South Africa              Etienne Le Riche is a total Cabernet specialis...
Spain                     Blackberry and raspberry aromas show a typical...
Switzerland               A Swiss blend of Pinot Noir and Gamay, this de...
Turkey                    From a winery that specializes in this rare va...
US                        Tart and snappy, the flavors of lime flesh and...
Ukraine                   On the nose, this nonvintage sparkler from the...
Uruguay                   Ripe earthy aromas of raisin and oaky vanilla ...
dtype: object

In [62]:
gk = reviews.groupby('country')
gk.first()

,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,
Argentina,"Baked plum, molasses, balsamic vinegar and che...",Felix,87,30.0,Other,Cafayate,NaN,Michael Schachner,@wineschach,Felix Lavaque 2010 Felix Malbec (Cafayate),Malbec,Felix Lavaque
Armenia,"Medium straw in the glass, this wine has a nos...",Estate Bottled,87,14.0,Armenia,NaN,NaN,Mike DeSimone,@worldwineguys,Van Ardi 2015 Estate Bottled Kangoun (Armenia),Kangoun,Van Ardi
Australia,This medium-bodied Chardonnay features aromas ...,Made With Organic Grapes,86,18.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Yalumba 2016 Made With Organic Grapes Chardonn...,Chardonnay,Yalumba
Austria,"Freshness characterizes the nose: green pear, ...",Schiefer Reserve,88,12.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Fuchs 2015 Grüner Veltliner (Burgenland),Grüner Veltliner,Fuchs
Bosnia and Herzegovina,"Toasted oak and cedar notes meld into lush, ri...",Vranac,85,13.0,Mostar,NaN,NaN,Anna Lee C. Iijima,@worldwineguys,Winery Čitluk 2007 Vranac Vranec (Mostar),Vranec,Winery Čitluk
Brazil,"Pear, apple and wet-stone aromas are tight, wh...",Brut,88,36.0,Pinto Bandeira,NaN,NaN,Michael Schachner,@wineschach,Cave Geisse 2014 Brut Sparkling (Pinto Bandeira),Sparkling Blend,Cave Geisse
Bulgaria,This pale-pink rosé is comprised of 70% Pinot ...,Veni Vidi Vici,86,9.0,Thracian Valley,NaN,NaN,Jeff Jenssen,@worldwineguys,Vini 2016 Veni Vidi Vici Rosé (Thracian Valley),Rosé,Vini
Canada,"An aromatic knockout with notes of peach, papa...",Reserve Icewine,92,30.0,Ontario,Niagara-On-The-Lake,NaN,Sean P. Sullivan,@wawinereport,Pillitteri 2012 Reserve Icewine Vidal (Niagara...,Vidal,Pillitteri
Chile,"White flower, lychee and apple aromas carry th...",Estate,86,15.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Estampa 2011 Estate Viognier-Chardonnay (Colch...,Viognier-Chardonnay,Estampa
China,This deep ruby-colored wine features a bouquet...,Noble Dragon,89,18.0,China,NaN,NaN,Mike DeSimone,@worldwineguys,Chateau Changyu-Castel 2009 Noble Dragon Red (...,Cabernet Blend,Chateau Changyu-Castel
Croatia,"Salt air, lemon pith and lemon blossom lead in...",Plavac Mali and Zinfandel,88,20.0,Istria,NaN,NaN,Jeff Jenssen,@worldwineguys,Coronica 2012 Malvasia (Istria),Malvasia,Coronica
Cyprus,"An alluring nose of apples, flowers and citrus...",Ayios Andronicos,85,17.0,Cyprus,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Chrysorroyiatissa 2008 Ayios Andronicos White ...,White Blend,Chrysorroyiatissa
Czech Republic,Smoke and struck-flint notes add a dark tone t...,Michlovský,85,25.0,Moravia,NaN,NaN,Anna Lee C. Iijima,@worldwineguys,Vino z Czech 2011 Welschriesling (Moravia),Welschriesling,Vino z Czech
Egypt,"Ripe pear, apple and tropical fruit in the nos...",Caspar Blanc de Noirs,84,NaN,Egypt,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Sahara Vineyards 2008 Caspar Blanc de Noirs Gr...,Grenache,Sahara Vineyards
England,A mix of fruity notes immediately hit: white c...,Blanc de Blancs,90,46.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Ridgeview Estate 2011 Blanc de Blancs Chardonn...,Chardonnay,Ridgeview Estate
France,This dry and restrained wine offers spice in p...,Les Natures,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
Georgia,"Deep ruby in the glass, this wine offers a bou...",Mukuzani,88,12.0,Kakheti,NaN,NaN,Mike DeSimone,@worldwineguys,Wine Man 2014 Mukuzani Saperavi (Kakheti),Saperavi,Wine Man
Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,@JoeCz,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel
Greece,"Lively aromas of lemon, grapefruit and melon s...",Asirtiko Athiri,89,15.0,Santorini,NaN,NaN,Susan Kostrzewa,@suskostrzewa,My Big Fat Greek Wine 2010 Assyrtico (Santorini),Assyrtico,My Big Fat Greek Wine
Hungary,From a vineyard in Northern Tokaj this dry Fur...,Megyer Dry,90,36.0,Tokaj,NaN,NaN,Jeff Jenssen,@worldwineguys,Samuel Tinon 2015 Megyer Dry Furmint (Tokaj),Furmint,Samuel Tinon
India,"The nose carries notes of cassis, blackberry a...",Dindori Reserve,93,20.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2011 Dindori Reserve Shiraz (Nashik),Shiraz,Sula
Israel,This wine features pleasing aromas of raspberr...,French Blend,90,50.0,Judean Hills,NaN,NaN,Mike DeSimone,@worldwineguys,Yatir 2011 Syrah (Judean Hills),Syrah,Yatir
Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,16.0,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
Lebanon,"Violet red to the eye, this wine is a blend of...",El,91,75.0,Lebanon,NaN,NaN,Mike DeSimone,@worldwineguys,Ixsir 2011 El Red (Lebanon),Red Blend,Ixsir
Luxembourg,This non vintage white blend is composed of 50...,Pinot Luxembourg,89,16.0,Moselle Luxembourgeoise,NaN,NaN,Jeff Jenssen,@worldwineguys,Domaines Vinsmoselle NV Pinot Luxembourg White...,White Blend,Domaines Vinsmoselle
Macedonia,"Snappy lemon, grapefruit and apples aromas lea...",Veritas,88,15.0,Tikves,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Bovin 2007 Sauvignon (Tikves),Sauvignon,Bovin
Mexico,"The color is appropriately light, the aromas a...",Private Reserve,88,18.0,Valle de Guadalupe,NaN,NaN,Michael Schachner,@wineschach,L.A. Cetto 1996 Private Reserve Nebbiolo (Vall...,Nebbiolo,L.A. Cetto
Moldova,This zesty Moldovan Feteasca Regala has aromas...,D'Or,87,11.0,Moldova,NaN,NaN,Jeff Jenssen,@worldwineguys,Château Vartely 2014 D'Or Feteascǎ Regalǎ (Mol...,Feteascǎ Regalǎ,Château Vartely
Morocco,"Deep garnet to the eye, this wine offers a nos...",Kahina,90,18.0,Zenata,NaN,NaN,Mike DeSimone,@worldwineguys,Ouled Thaleb 2013 Syrah (Zenata),Syrah,Ouled Thaleb
New Zealand,The Stoneleigh style traditionally favors ripe...,Pioneer Block 20 Dillons Point Cash Block,88,19.0,Marlborough,NaN,NaN,Joe Czerwinski,@JoeCz,Stoneleigh 2008 Sauvignon Blanc (Marlborough),Sauvignon Blanc,Stoneleigh
Peru,Aromas of freshly laid asphalt and char-grille...,Valle del Sol,85,14.0,Ica,NaN,NaN,Michael Schachner,@wineschach,Intipalka 2013 Valle del Sol Tannat (Ica),Tannat,Intipalka
Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
Romania,"Fragrant on the nose with fresh orange, lemon ...",Rosso di Valachia,87,7.0,Recas,NaN,NaN,Anna Lee C. Iijima,@suskostrzewa,Cramele Recas 2009 Chardonnay (Recas),Chardonnay,Cramele Recas
Serbia,This white wine from Serbia has aromas of cara...,Portuguiser,87,26.0,Pocerina,NaN,NaN,Jeff Jenssen,@worldwineguys,Milijan Jelić 2011 Morava (Pocerina),Morava,Milijan Jelić
Slovakia,"Delicious scents of honey, apples and petrol l...",NaN,87,16.0,Muzla,NaN,NaN,Anna Lee C. Iijima,NaN,Château Bela 2008 Riesling (Muzla),Riesling,Château Bela
Slovenia,Earthy with hints of roasted nuts and dried he...,Fosilni Breg,84,20.0,Slovenia,NaN,NaN,Anna Lee C. Iijima,@worldwineguys,Ciringa 2011 Fosilni Breg Sauvignon Blanc (Slo...,Sauvignon Blanc,Ciringa
South Africa,Etienne Le Riche is a total Cabernet specialis...,Cabernet Sauvignon Reserve,91,45.0,Stellenbosch,NaN,NaN,Roger Voss,@vossroger,Le Riche 2003 Cabernet Sauvignon Reserve Caber...,Cabernet Sauvignon,Le Riche
Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
Switzerland,"A Swiss blend of Pinot Noir and Gamay, this de...",Dôle des Monts,90,30.0,Valais,NaN,NaN,Jeff Jenssen,@worldwineguys,Robert Gilliard 2012 Dôle des Monts Pinot Noir...,Pinot Noir-Gamay,Robert Gilliard
Turkey,From a winery that specializes in this rare va...,Reserve Single Vineyard Bozokbag,88,20.0,Thrace,NaN,NaN,Mike DeSimone,@worldwineguys,Chamlija 2014 Papaskarasi (Thrace),Papaskarasi,Chamlija
US,"Tart and snappy, the flavors of lime flesh and...",Reserve Late Harvest,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
Ukraine,"On the nose, this nonvintage sparkler from the...",Brut,83,10.0,Ukraine,NaN,NaN,Jeff Jenssen,@worldwineguys,Marengo NV Brut Sparkling (Ukraine),Sparkling Blend,Marengo
Uruguay,Ripe earthy aromas of raisin and oaky vanilla ...,B2 Parcela Unica,88,43.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Bouza 2013 B2 Parcela Unica Tannat (Canelones),Tannat,Bouza

In [63]:
# Finding the values contained in the "India" group
gk.get_group('India')

,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
6673,"The nose carries notes of cassis, blackberry a...",Dindori Reserve,93,20.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2011 Dindori Reserve Shiraz (Nashik),Shiraz,Sula
29302,A nose of cut herbs and just-mown grass backed...,NaN,89,12.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2015 Sauvignon Blanc (Nashik),Sauvignon Blanc,Sula
37225,"Pineapple, grapefruit, and apricot show bright...",NaN,90,10.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2013 Chenin Blanc (Nashik),Chenin Blanc,Sula
56903,"Aromas of blackberry, cherry preserves, white ...",Estate Bottled,91,12.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2012 Estate Bottled Shiraz (Nashik),Shiraz,Sula
83622,"Pineapple, grapefruit, and apricot show bright...",NaN,90,10.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2013 Chenin Blanc (Nashik),Chenin Blanc,Sula
83634,"Aromas of pink grapefruit, grass and coriander...",NaN,90,12.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2013 Sauvignon Blanc (Nashik),Sauvignon Blanc,Sula
88134,"Dark violet-red in color, this wine has a bouq...",Estate Bottled,90,13.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2015 Estate Bottled Shiraz (Nashik),Shiraz,Sula
108251,"Deep garnet in the glass, this wine has a nose...",Dindori Reserve,92,19.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2014 Dindori Reserve Shiraz (Nashik),Shiraz,Sula
126932,This wine features a fresh nose of grapefruit ...,NaN,87,12.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2015 Chenin Blanc (Nashik),Chenin Blanc,Sula

In [64]:
# First grouping based on "Country"
# Within each team we are grouping based on "Province"
gkk = reviews.groupby(['country', 'province'])
  
# Print the first value in each group
gkk.first()

                                                                  description  \
country   province
Argentina Mendoza Province  Raw black-cherry aromas are direct and simple ...
          Other             Baked plum, molasses, balsamic vinegar and che...
Armenia   Armenia           Medium straw in the glass, this wine has a nos...
Australia Australia Other   Melon and citrus aromas and flavors mingle eas...
          New South Wales   This medium-bodied Shriaz displays a soft, cre...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        With attractive, authentic aromas of lemon, le...
          Progreso          RPF is regularly one of Uruguay's better Tanna...
          San Jose          Brambly and stalky berry fruit aromas come wit...
          Uruguay           Ripe berry and prune aromas are accented by li...

                                                 designation  points  price  \
country   province
Argentina Mendoza Province               Winemaker Selection      87   13.0
          Other                                        Felix      87   30.0
Armenia   Armenia                             Estate Bottled      87   14.0
Australia Australia Other                            Classic      85    9.0
          New South Wales                             Vision      88   13.0
...                                                      ...     ...    ...
Uruguay   Juanico           Preludio Barrel Select Lote N 77      90   45.0
          Montevideo                  100 Años Viñas Mendoza      90   25.0
          Progreso                                       RPF      88   20.0
          San Jose                             Parcela Vieja      83   20.0
          Uruguay                                      Roble      90   35.0

                                           region_1 region_2  \
country   province
Argentina Mendoza Province                  Mendoza      NaN
          Other                            Cafayate      NaN
Armenia   Armenia                               NaN      NaN
Australia Australia Other   South Eastern Australia      NaN
          New South Wales             Hunter Valley      NaN
...                                             ...      ...
Uruguay   Juanico                               NaN      NaN
          Montevideo                            NaN      NaN
          Progreso                              NaN      NaN
          San Jose                              NaN      NaN
          Uruguay                               NaN      NaN

                                  taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province  Michael Schachner           @wineschach
          Other             Michael Schachner           @wineschach
Armenia   Armenia               Mike DeSimone        @worldwineguys
Australia Australia Other      Joe Czerwinski                @JoeCz
          New South Wales      Joe Czerwinski                @JoeCz
...                                       ...                   ...
Uruguay   Juanico           Michael Schachner           @wineschach
          Montevideo        Michael Schachner           @wineschach
          Progreso          Michael Schachner           @wineschach
          San Jose          Michael Schachner           @wineschach
          Uruguay           Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Gaucho Andino 2011 Winemaker Selection Malbec ...
          Other                    Felix Lavaque 2010 Felix Malbec (Cafayate)
Armenia   Armenia              Van Ardi 2015 Estate Bottled Kangoun (Armenia)
Australia Australia Other   Jacob's Creek 2015 Classic Pinot Grigio (South...
          New South Wales             Hope Estate 2009 Shiraz (Hunter Valley)
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo                         Bouza 2013 Albariño (Montevideo)
          Progreso                          Pisano 2013 RPF Tannat (Progreso)
          San Jose          Castillo Viejo 2007 Parcela Vieja Tannat (San ...
          Uruguay                         Narbona 2013 Roble Tannat (Uruguay)

                                 variety          winery
country   province
Argentina Mendoza Province        Malbec   Gaucho Andino
          Other                   Malbec   Felix Lavaque
Armenia   Armenia                Kangoun        Van Ardi
Australia Australia Other   Pinot Grigio   Jacob's Creek
          New South Wales         Shiraz     Hope Estate
...                                  ...             ...
Uruguay   Juanico              Red Blend  Familia Deicas
          Montevideo            Albariño           Bouza
          Progreso                Tannat          Pisano
          San Jose                Tannat  Castillo Viejo
          Uruguay                 Tannat         Narbona

[425 rows x 11 columns]

In [65]:
reviews.groupby(['country']).price.agg([len, min, max])

#Another groupby() method worth mentioning is agg(),
#which lets you run a bunch of different functions on your DataFrame simultaneously.

                            len   min     max
country
Argentina                3800.0   4.0   230.0
Armenia                     2.0  14.0    15.0
Australia                2329.0   5.0   850.0
Austria                  3345.0   7.0  1100.0
Bosnia and Herzegovina      2.0  12.0    13.0
Brazil                     52.0  10.0    60.0
Bulgaria                  141.0   8.0   100.0
Canada                    257.0  12.0   120.0
Chile                    4472.0   5.0   400.0
China                       1.0  18.0    18.0
Croatia                    73.0  12.0    65.0
Cyprus                     11.0  11.0    21.0
Czech Republic             12.0  15.0    45.0
Egypt                       1.0   NaN     NaN
England                    74.0  25.0    95.0
France                  22093.0   5.0  3300.0
Georgia                    86.0   9.0    40.0
Germany                  2165.0   5.0   775.0
Greece                    466.0   8.0    79.0
Hungary                   146.0  10.0   764.0
India                       9.0  10.0    20.0
Israel                    505.0   8.0   150.0
Italy                   19540.0   5.0   900.0
Lebanon                    35.0  13.0    75.0
Luxembourg                  6.0  16.0    30.0
Macedonia                  12.0  15.0    20.0
Mexico                     70.0   8.0   108.0
Moldova                    59.0   8.0    42.0
Morocco                    28.0  14.0    40.0
New Zealand              1419.0   7.0   130.0
Peru                       16.0  10.0    68.0
Portugal                 5691.0   5.0  1000.0
Romania                   120.0   4.0   320.0
Serbia                     12.0  15.0    42.0
Slovakia                    1.0  16.0    16.0
Slovenia                   87.0   7.0    90.0
South Africa             1401.0   5.0   330.0
Spain                    6645.0   4.0   770.0
Switzerland                 7.0  21.0   160.0
Turkey                     90.0  14.0   120.0
US                      54504.0   4.0  2013.0
Ukraine                    14.0   6.0    13.0
Uruguay                   109.0  10.0   130.0

In [66]:
# A multi-index differs from a regular index in that it has multiple levels
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85
...                          ...
Uruguay   Juanico             12
          Montevideo          11
          Progreso            11
          San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [67]:
countries_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [68]:
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

          country               province    len
179        Greece  Muscat of Kefallonian      1
192        Greece          Sterea Ellada      1
194        Greece                 Thraki      1
354  South Africa             Paardeberg      1
40         Brazil       Serra do Sudeste      1
..            ...                    ...    ...
409            US                 Oregon   5373
227         Italy                Tuscany   5897
118        France               Bordeaux   5941
415            US             Washington   8639
392            US             California  36247

[425 rows x 3 columns]

In [69]:
countries_reviewed.sort_values(by='len', ascending=False)

          country         province    len
392            US       California  36247
415            US       Washington   8639
118        France         Bordeaux   5941
227         Italy          Tuscany   5897
409            US           Oregon   5373
..            ...              ...    ...
101       Croatia              Krk      1
247   New Zealand        Gladstone      1
357  South Africa  Piekenierskloof      1
63          Chile          Coelemu      1
149        Greece           Beotia      1

[425 rows x 3 columns]

In [70]:
countries_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [71]:
countries_reviewed.sort_values(by=['country', 'len'])

       country          province   len
1    Argentina             Other   536
0    Argentina  Mendoza Province  3264
2      Armenia           Armenia     2
6    Australia          Tasmania    42
4    Australia   New South Wales    85
..         ...               ...   ...
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
420    Uruguay           Juanico    12
424    Uruguay           Uruguay    24
419    Uruguay         Canelones    43

[425 rows x 3 columns]